version: '3.7'
services:
  authentication_1:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
  authentication_2:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8080"
  authentication_3:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8082:8080"
  haproxy:
    image: haproxy:1.9
    volumes:
      - ${PWD}/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}/config/myselfsigned.pem:/etc/ssl/myselfsigned.pem
    ports:
      - 80:80
      - 443:443
    container_name: haproxy