version: '3.7'
services:
  authentication_1:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
    - ${PWD}/facebook_configuration.json:/rust/facebook_configuration.json
    - ${PWD}/config/mysql_configuration.json:/rust/mysql_configuration.json
#  authentication_2:
#    build:
#      context: ./
#      dockerfile: Dockerfile-dev
#    ports:
#      - "8081:8080"
#  authentication_3:
#    build:
#      context: ./
#      dockerfile: Dockerfile-dev
#    ports:
#      - "8082:8080"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
      - ${PWD}/config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
    container_name: mysql
  haproxy:
    image: haproxy:1.9
    volumes:
      - ${PWD}/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}/config/myselfsigned.pem:/etc/ssl/myselfsigned.pem
    ports:
      - 80:80
      - 443:443
    container_name: haproxy
volumes:
  db-vol: